# These are supported funding model platforms
# jeder, der viel an der webseite gemacht hat - darf sich hier *natürlich* verlinken!

github: [DO1JLR]
liberapay: L3D
custom: ['https://ffbsee.net/helfen/', 'https://freifunk-bodensee.net/helfen/#code']
