language: python
python: 3.6
branches:
  only:
  - master
git:
  lfs_skip_smudge: true
cache:
  directories:
    - $HOME/.cache/pip
    - .git/lfs
before_install:
  - git lfs pull
install:
  - pip3 install lektor

script: "make build"

before_deploy:
  - "echo 'ffbsee.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBFeaPH+onFycj5nldRpRJtcstlYMosQJSv2iwXEA05/3Zv2RA5pUdBWgv48AA06hQlnp7TA/SCQyM+mCNXW3uEQ=' > ~/.ssh/known_hosts"
  - "echo 'ffbsee.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDSWASdI5hMoq4pIEPgINEVljbK4zbOtaX9DSqtevtXi' >> ~/.ssh/known_hosts"
  - "echo 'ffbsee.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDvlRfU/8X1JBM1VxuYBg+svXfpacQKmVnsF2GVSgAvIuUFKAVsgpH8/ge6DsVhGT5tifjGfzPsi44lO471pc+W3y7Eiu1mhtutiR68JqGafFfv3onEoX9Bt01M8ueA1vyXqHuVHGXi6O+YgpM8BXaCHI1/cHYPD13pDXlp7ZXVNKaWRvsiRwGL5EJwaMdAGabS3nWNwAbxMTzvdJjsW5zY4+lYCfSvwrcm7F7FEpjzRdT9DIXD7SkaeHk98N+5uIrgnwzhmn1yYrkymFQbge5iIvpD4jqSaUePRBPI7d9VyFJXJXLy1arpFbAkRzTm0Gzg41vY5Yd0Y97HmH0xbqZ/' >> ~/.ssh/known_hosts"
deploy:
  provider: script
  script: "lektor deploy --key $LEKTOR_DEPLOY_KEY ffbsee"
