language: python
python: 3.6
branches:
  only:
  - master
git:
  lfs_skip_smudge: true
cache:
  directories:
    - $HOME/.cache/pip
    - .git/lfs
before_install:
  - git lfs pull
install:
  - pip3 install lektor

script: "make build"

before_deploy:
  - "echo 'ffbsee.net ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBC5NslYj+wtriBuKIxJfDRm9E2hnlstWR8durQ6pKvVvP7wjcoXIyAxe41GvJ9SoEhSjF7oVlzlw+zAkzl5WOZ4=' > ~/.ssh/known_hosts"
  - "echo 'ffbsee.net ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICPjpWvNTpw08/uTX0vTAZVDUDSxFOexeqqkWxqDBSM3' >> ~/.ssh/known_hosts"
  - "echo 'ffbsee.net ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDIq9jSnxybmYM0Qhhf6Q/L3vRSdVOL4Yk2KPHU9dTahCK9UMTVHa+klUKwhk8ObYV27Q40HaREJypMSejIocMUp1WQVBPzL/krLgKGnBjy+zo3GVR9oculcc5XfzyMG6fY2YoEfJB2Mgd5pXUD9J9sIWj7x5oXcLT0koehaUnDyVYfX3YMT9tfutUI1juzI/VMwyC4nhGsdyjYNe5CEYi7Xfr39Gb7m/lk38zRH1HdWq3vyd8VzVo6PFUZZTC58GIWgvGX7PVGMHU2tmtVixoDynXyMPik0P+QfignSqQqL+sbEyG0dynZBOFkhy6bt8Z58jjaLZI/C+kgd+YIuEMX' >> ~/.ssh/known_hosts"
deploy:
  provider: script
  script: "lektor deploy --key $LEKTOR_DEPLOY_KEY ffbsee"
